import type { Driver } from "./types";

export const CHECKPOINTS = [
  "KWS",
  "TOOLCRAFTS",
  "AUTO XPRESS",
  "SATAO",
  "OCEAN AGRICULTURE",
  "MANTECH",
  "TIRE WORLD",
  "GRIDLESS",
  "COPY CAT",
  "AQUAMIST",
  "FLOWERWATCH",
  "SOLEX",
  "SLATER & WHITTAKER",
] as const;

export type CheckpointName = (typeof CHECKPOINTS)[number];

export const INITIAL_DRIVERS: Driver[] = [
  {
    id: 1,
    carNo: "001",
    entrantName: "Kalle Rovanperä",
    teamName: "Toyota Gazoo Racing WRT",
    checkpoints: {
      KWS: "START",
      TOOLCRAFTS: "START",
      "AUTO XPRESS": "START",
      SATAO: "START",
      "OCEAN AGRICULTURE": "START",
      MANTECH: "START",
      "TIRE WORLD": "START",
      GRIDLESS: "START",
      "COPY CAT": "START",
      AQUAMIST: "START",
      FLOWERWATCH: "START",
      SOLEX: "",
      "SLATER & WHITTAKER": "",
    },
    totalCps: 11,
  },
  {
    id: 2,
    carNo: "002",
    entrantName: "Sébastien Ogier",
    teamName: "Toyota Gazoo Racing WRT",
    checkpoints: {
      KWS: "START",
      TOOLCRAFTS: "START",
      "AUTO XPRESS": "START",
      SATAO: "START",
      "OCEAN AGRICULTURE": "START",
      MANTECH: "START",
      "TIRE WORLD": "START",
      GRIDLESS: "START",
      "COPY CAT": "START",
      AQUAMIST: "START",
      FLOWERWATCH: "",
      SOLEX: "",
      "SLATER & WHITTAKER": "",
    },
    totalCps: 10,
  },
  {
    id: 3,
    carNo: "011",
    entrantName: "Thierry Neuville",
    teamName: "Hyundai Shell Mobis WRT",
    checkpoints: {
      KWS: "START",
      TOOLCRAFTS: "START",
      "AUTO XPRESS": "START",
      SATAO: "START",
      "OCEAN AGRICULTURE": "START",
      MANTECH: "START",
      "TIRE WORLD": "START",
      GRIDLESS: "START",
      "COPY CAT": "START",
      AQUAMIST: "",
      FLOWERWATCH: "",
      SOLEX: "",
      "SLATER & WHITTAKER": "",
    },
    totalCps: 9,
  },
  {
    id: 4,
    carNo: "033",
    entrantName: "Elfyn Evans",
    teamName: "Toyota Gazoo Racing WRT",
    checkpoints: {
      KWS: "START",
      TOOLCRAFTS: "START",
      "AUTO XPRESS": "START",
      SATAO: "START",
      "OCEAN AGRICULTURE": "START",
      MANTECH: "START",
      "TIRE WORLD": "START",
      GRIDLESS: "START",
      "COPY CAT": "",
      AQUAMIST: "",
      FLOWERWATCH: "",
      SOLEX: "",
      "SLATER & WHITTAKER": "",
    },
    totalCps: 8,
  },
  {
    id: 5,
    carNo: "008",
    entrantName: "Ott Tänak",
    teamName: "Hyundai Shell Mobis WRT",
    checkpoints: {
      KWS: "START",
      TOOLCRAFTS: "START",
      "AUTO XPRESS": "START",
      SATAO: "START",
      "OCEAN AGRICULTURE": "START",
      MANTECH: "START",
      "TIRE WORLD": "START",
      GRIDLESS: "",
      "COPY CAT": "",
      AQUAMIST: "",
      FLOWERWATCH: "",
      SOLEX: "",
      "SLATER & WHITTAKER": "",
    },
    totalCps: 7,
  },
  {
    id: 6,
    carNo: "016",
    entrantName: "Adrien Fourmaux",
    teamName: "M-Sport Ford WRT",
    checkpoints: {
      KWS: "START",
      TOOLCRAFTS: "START",
      "AUTO XPRESS": "START",
      SATAO: "START",
      "OCEAN AGRICULTURE": "START",
      MANTECH: "START",
      "TIRE WORLD": "",
      GRIDLESS: "",
      "COPY CAT": "",
      AQUAMIST: "",
      FLOWERWATCH: "",
      SOLEX: "",
      "SLATER & WHITTAKER": "",
    },
    totalCps: 6,
  },
  {
    id: 7,
    carNo: "022",
    entrantName: "Grégoire Munster",
    teamName: "Hyundai Shell Mobis WRT",
    checkpoints: {
      KWS: "START",
      TOOLCRAFTS: "START",
      "AUTO XPRESS": "START",
      SATAO: "START",
      "OCEAN AGRICULTURE": "START",
      MANTECH: "",
      "TIRE WORLD": "",
      GRIDLESS: "",
      "COPY CAT": "",
      AQUAMIST: "",
      FLOWERWATCH: "",
      SOLEX: "",
      "SLATER & WHITTAKER": "",
    },
    totalCps: 5,
  },
  {
    id: 8,
    carNo: "044",
    entrantName: "Yohan Rossel",
    teamName: "PH Sport Citroën",
    checkpoints: {
      KWS: "START",
      TOOLCRAFTS: "START",
      "AUTO XPRESS": "START",
      SATAO: "START",
      "OCEAN AGRICULTURE": "",
      MANTECH: "",
      "TIRE WORLD": "",
      GRIDLESS: "",
      "COPY CAT": "",
      AQUAMIST: "",
      FLOWERWATCH: "",
      SOLEX: "",
      "SLATER & WHITTAKER": "",
    },
    totalCps: 4,
  },
  {
    id: 9,
    carNo: "055",
    entrantName: "Nikolay Gryazin",
    teamName: "Toksport WRT Škoda",
    checkpoints: {
      KWS: "START",
      TOOLCRAFTS: "START",
      "AUTO XPRESS": "START",
      SATAO: "",
      "OCEAN AGRICULTURE": "",
      MANTECH: "",
      "TIRE WORLD": "",
      GRIDLESS: "",
      "COPY CAT": "",
      AQUAMIST: "",
      FLOWERWATCH: "",
      SOLEX: "",
      "SLATER & WHITTAKER": "",
    },
    totalCps: 3,
  },
  {
    id: 10,
    carNo: "077",
    entrantName: "Georg Linnamäe",
    teamName: "Toyota Gazoo Racing WRT",
    checkpoints: {
      KWS: "START",
      TOOLCRAFTS: "START",
      "AUTO XPRESS": "",
      SATAO: "",
      "OCEAN AGRICULTURE": "",
      MANTECH: "",
      "TIRE WORLD": "",
      GRIDLESS: "",
      "COPY CAT": "",
      AQUAMIST: "",
      FLOWERWATCH: "",
      SOLEX: "",
      "SLATER & WHITTAKER": "",
    },
    totalCps: 2,
  },
];
